# Site settings
title: reverse engineers
email: weeri@rev.engineering
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:
facebook_username: reversengineers
instagram_username: reverse.engineers
youtube_username: UCVzMry2PfkaisRTrgLef4jw

# Build settings
markdown: kramdown
